name: Generate BuildingBloCS Static Site
on: 
  push:
      branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  gen-site:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Github Pages Default Workflow
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: 18607871
          access_token: ${{ github.token }}
      # Checks out all history
      - name: Checkout main brach
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
    
      # Build static site
      - name: Install Gems and build static site
        run: |
          git checkout -b _site
          bundle install --full-index
          bundle exec jekyll build
          rm -rf !(_site)
          mv _site/* ./
          rm _site/yarn.lock
      - name: Commit to branch
        uses: EndBug/add-and-commit@v9
        with:
          add: '. -f'
          default_author: github_actions
          message: "Pushing new version of i18n site"
          push: 'origin _site --force'
